/* Autogenerated, do not edit */
#define gss_data_bootstrap_responsive_css_len  14308
extern const char gss_data_bootstrap_responsive_css[];
#define gss_data_bootstrap_css_len  98995
extern const char gss_data_bootstrap_css[];
#define gss_data_bootstrap_js_len  50089
extern const char gss_data_bootstrap_js[];
#define gss_data_footer_entropywave_png_len  9586
extern const char gss_data_footer_entropywave_png[];
#define gss_data_glyphicons_halflings_white_png_len  8777
extern const char gss_data_glyphicons_halflings_white_png[];
#define gss_data_glyphicons_halflings_png_len  13826
extern const char gss_data_glyphicons_halflings_png[];
#define gss_data_include_js_len  13142
extern const char gss_data_include_js[];
#define gss_data_jquery_js_len  247823
extern const char gss_data_jquery_js[];
#define gss_data_offline_png_len  1413
extern const char gss_data_offline_png[];
#define gss_data_no_snapshot_png_len  1702
extern const char gss_data_no_snapshot_png[];
